os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode9
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            HOMEBREW_NO_AUTO_UPDATE=1 brew install vapor/tap/vapor vapor/tap/cmysql;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo apt-get install cmysql;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build -Xswiftc -DNOJSON
    - swift build -c release -Xswiftc -DNOJSON
    - swift test -Xswiftc -DNOJSON

after_success:
    - eval "$(curl -sL https://raw.githubusercontent.com/vapor-community/swift/swift-4-codecov/codecov-swift4)"

notifications:
  email:
    on_success: change
    on_failure: change
